### ISSUE TITLE
animated-directional-chord-diagrams.Rmd creates plots different than the blog

### ISSUE THREAD

**Issue by BFODonnell** [guyabel/personal-site#1]
When I run the code it creates 100 chord diagrams which are identical and incorrect.  The 'connecting bands' all have points on both ends.  Below is an example diagram.

![globalchord0](https://user-images.githubusercontent.com/16277899/54617822-64b94c00-4a38-11e9-9d64-c437d9378030.png)

**Comment by gjabel** [comment]
I think this is an issue related to the new update in circlize. I managed to sort things out in my code by only passing three columns to the `x` argument in `chordDiagram()`, i.e. 
```
    chordDiagram(x = d2 %>% 
                   filter(.frame == f) %>%
                   select(1:3), 
                # all other arguments as before
                directional = 1, order = d1$reg_name, ...
```
